name: Compress

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    if: github.repository == 'doocs/jvm'
    steps:
      - name: Checkout Branch
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@9d037c06280028c110ff61c433ad4dc7d33c3c43 # 1.5.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true

      - name: Commit Files
        if: |
          steps.calibre.outputs.markdown != ''
        run: |
          git config --local user.email "szuyanglb@outlook.com"
          git config --local user.name "yanglbme"
          git commit -m "chore: auto compress images" -a

      - name: Push Changes
        if: |
          steps.calibre.outputs.markdown != ''
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
